# config.yaml
# Updated to include aliases for the Kubernetes clients.

sdks:
  kubernetes:
    enabled: true
    client_factory:
      path: "core.clients.init_kubernetes_clients"
    
    classes_to_expose:
      - class_path: "kubernetes.client.CoreV1Api"
        # **NEW**: Alias for the Core API
        alias: "k8s_core"
        include_methods:
          - "list_pod_for_all_namespaces"
          - "list_namespaced_pod"
          - "read_namespaced_pod"
          - "delete_namespaced_pod"
          - "list_service_for_all_namespaces"
          - "list_namespaced_service"
          - "read_namespaced_service"
          - "list_namespace"
          - "read_namespace"
          - "list_namespaced_config_map"
          - "read_namespaced_config_map"
          - "list_namespaced_secret"
          - "read_namespaced_secret"

      - class_path: "kubernetes.client.AppsV1Api"
        # **NEW**: Alias for the Apps API
        alias: "k8s_apps"
        include_methods:
          - "list_deployment_for_all_namespaces"
          - "list_namespaced_deployment"
          - "read_namespaced_deployment"
          - "delete_namespaced_deployment"
          - "list_namespaced_stateful_set"
          - "read_namespaced_stateful_set"
          - "list_namespaced_daemon_set"
          - "read_namespaced_daemon_set"
